SKRF-142 design: 헤더 레이아웃 공통 컴포넌트 구현
Space-Club/Frontend pull request #20
Opened 2023-10-25 04:57 UTC by colorkite10

## 📝요구사항과 구현내용
- 헤더 레이아웃 공통 컴포넌트를 구현했습니다. 
- 혜성님이 말씀하신 바를 이해한 대로 만들어보았습니다...

- `page: 'main' | 'club'`
메인 페이지와 클럽 페이지의 헤더가 다르므로 `page`로 구분합니다. 
- 사용할 때는 헤더에 포함해줄 요소들을 `<Header></Header>`로 묶어주시면 됩니다. 

## 구현 스크린샷
![image](https://github.com/Space-Club/Frontend/assets/98521882/69e8c797-b6d4-4ac3-b1fb-41dc6ad49537)

## ✨pr포인트 & 궁금한 점 
- 많은 피드백 환영합니다. 감사합니다!

2023-10-25 05:26 UTC, hyesung99 requested changes
제 말이 정답은 아니니 비판적인 피드백 수용 부탁드립니다 하하..

2023-10-25 05:26 UTC, hyesung99 commented on src/components/common/Header/Header.tsx
> +  page: 'main' | 'club';
p2;
제 생각에는 이 헤더 컴포넌트는 main,club과는 무관하게 가야된다고 생각합니다! 도메인을 모르는 컴포넌트가 되는거죠!
예를들어 만약 main,club이외에 profile이라는 도메인이 추가된다면 이 파일도 수정되어야 할거에요! 그렇다면 적절히 추상화가 되지 않은 상태겠죠?

헤더 컴포넌트는 딱 왼쪽에 로고와 페이지 상위에 붙는 역할, 그리고 children컴포넌트들을 로고 오른쪽에 정렬하는 것만으로 역할을 제한해야한다고 생각해요.

children에 관한 내용은 전부 부모컴포넌트에 위임하는거죠!

그러면 다른 도메인이 추가되어도 이 파일은 수정될 필요가 없을것 같아요!

2023-10-25 05:26 UTC, hyesung99 commented on src/components/common/Header/Header.tsx
> +      </OptionWrapperStyled>
```suggestion
      <ChildrenContainerStyled>{children}</ChildrenStyled>
```
제가 위에서 리뷰한걸 적용하면 이런 구조가 되겠네요!

2023-10-25 05:26 UTC, hyesung99 commented on src/components/common/Header/Header.style.ts
> +  width: 75%;
p2;
children의 width는 로고를 뺀 나머지 width면 좋을것 같아요!
calc(100%-로고사이즈) or flex-grow: 1;

2023-10-25 05:26 UTC, hyesung99 commented on src/components/common/Header/Header.style.ts
> +  justify-content: ${({ page }) => (page === 'main' ? 'space-between' : 'flex-end')};
p2;
생각해보니 children에 대한 position을 설정해주지 않아도 될것 같네요...!ㅠ
죄송함다ㅠ
children컨테이너 로고를 뺸 나머지 너비를 width로만 지정해주면 그 안에선 부모 컴포넌트가 알아서 하게 만들면 될 것...같아요!

2023-10-25 05:26 UTC, hyesung99 commented on src/components/common/Header/Header.style.ts
> +`;
p3;
children컨테이너(figma기준 빨간박스) 내부의 스타일은 부모 컴포넌트에게 위임하는게 좋을것 같아요!

2023-10-25 06:54 UTC, SongInjae approved these changes
제가 리뷰해드릴 부분은 없는 것 같습니다....😅 고생하셨습니다:)

2023-10-25 12:43 UTC, SongInjae approved these changes
고생하셨습니다:)

2023-10-26 04:25 UTC, hyesung99 approved these changes

2023-10-26 04:25 UTC, merged