design: layout ui 적용
Space-Club/Frontend pull request #24
Opened 2023-10-25 09:39 UTC by SongInjae

## 📝요구사항과 구현내용
- 작업 내용 1: layout UI를 구현했습니다.

## 구현 스크린샷
<img width="1440" alt="스크린샷 2023-10-25 오후 6 36 48" src="https://github.com/Space-Club/Frontend/assets/44944877/9e44c6b6-636e-4db5-809c-18cabdbc9749">

## ✨pr포인트 & 궁금한 점 
- layout 부분 ui 수정할 곳이 있는지 궁금합니다.
- 더 깔끔하게 코드 짤 곳이 있을까요?

2023-10-25 13:35 UTC, colorkite10 submitted a review, later dismissed
수고하셨습니다! :)

2023-10-25 13:35 UTC, colorkite10 commented on src/pages/Layout/SideNav.style.ts
> +`;
p5; 관련 있는 스타일 속성끼리 묶어서 작성하면 보기에 편할 것 같습니다! 
저는 주로 아래 링크를 참고합니다! 
https://uxkm.io/publishing/css/03-cssMiddleclass/10-css_attr_rule#gsc.tab=0

2023-10-25 13:35 UTC, colorkite10 commented on src/pages/Layout/SideNav.tsx
> +const SideNav = ({ name = '무명' }: SideNav) => {
본인 프로필 하단에 닉네임 나오지 않도록 구두로 얘기했었는데(이유: 닉네임이 길어질 경우 안 예쁨) 인재님한테 전달한다는 걸 깜빡했네요 😂😂
나중에 사용하는 사람이 겸사겸사 수정하면 될 것 같습니다.

2023-10-25 13:35 UTC, colorkite10 commented on src/pages/Layout/SideNav.tsx
> +          ))}
Array(8)로 고정하신 이유가 궁금합니다...! 그리고 club아이디를 넘겨줘야 하지 않나요?

2023-10-26 01:15 UTC, hyesung99 requested changes
👍

2023-10-26 01:15 UTC, hyesung99 commented on src/pages/Layout/SideNav.tsx
> +        <ProfileAvatar avatarShape="rectangle" />
p2;
스타일을 상속하기 보다는 컴포넌트를 바로 import해서 가져오면 될것 같아요!
```suggestion
        <Avatar avatarShape="rectangle" />
```

2023-10-26 01:15 UTC, hyesung99 commented on src/pages/Layout/SideNav.tsx
> +          ))}
p1;
  ```jsx
  const { data: user } = useQuery('user', getUser);
  return (
    <Container>
      <AvatarGroup>
        {user.clubs.map((club) => (
          <Avatar key={club.id} avatarShape="normal">
            <Link to={`/club/${club.id}`} />
          </Avatar>
        ))}
```
이런식으로 api연결도 해야할것 같네요! user정보를 get하는 api가 필요할것 같은데 아직 명세에 없어서 백엔드랑 협의해야겠어요!

그리고 avatar내부에 Link나 a태그를 넣어서 라우팅도 구현해주세요!

2023-10-26 01:22 UTC, hyesung99 commented on src/pages/Layout/Layout.tsx
> +    <Container>
p2;
스크롤을 위한 컨테이너는 common에 VerticalScorll 컴포넌트를 사용해주세요! 추후에 스크롤 디지인도 해당 컴포넌트에 추가하겠습니다

2023-10-26 04:58 UTC, SongInjae commented on src/pages/Layout/SideNav.tsx
> +const SideNav = ({ name = '무명' }: SideNav) => {
아하 그렇군요.... 수정하겠습니다:)

2023-10-26 05:00 UTC, SongInjae commented on src/pages/Layout/SideNav.tsx
> +          ))}
처음에 UI만 만든 생각으로 한 부분입니다!
API까지 연동해서 재커밋 올리겠습니다:)

2023-10-26 08:31 UTC, SongInjae commented on src/pages/Layout/Layout.tsx
> +    <Container>
네 알겠습니다:)

2023-10-26 08:31 UTC, SongInjae commented on src/pages/Layout/SideNav.tsx
> +          ))}
넵 이부분 적용했습니다!
희한하게 Avatar안에 Link를 두면 안되더라구요...ㅠㅡㅠ Avatar에 onClick해도 안되구...
그래서 Link로 겉에 감싸안았습니다! 감사합니다:)

2023-10-26 08:32 UTC, SongInjae commented on src/pages/Layout/SideNav.tsx
> +        <ProfileAvatar avatarShape="rectangle" />
넵 적용했습니다!

2023-10-26 08:32 UTC, SongInjae commented on src/pages/Layout/SideNav.style.ts
> +  padding: 1rem 0;
오옹 사용자가 느끼기엔 이상하다고 생각하겠군요!
적용했습니다! 감사합니다:)

2023-10-26 08:32 UTC, SongInjae commented on src/pages/Layout/SideNav.style.ts
> +  overflow: scroll;
오옹 처음 알았군요.... 감사합니다:)

2023-10-26 08:33 UTC, SongInjae commented on src/pages/Layout/SideNav.style.ts
> +`;
넵 적용했습니다! 감사합니다:)

2023-10-26 11:42 UTC, hyesung99 commented on src/App.tsx
> +    </div>
p2;
QueryClient삭제하신 이유가 있을까요?

2023-10-26 12:17 UTC, hyesung99 submitted a review, later dismissed
승인 눌렀습니다! 리뷰 한번 확인하고 적용할만한건 적용해주세요!👍

2023-10-26 12:17 UTC, hyesung99 commented on src/pages/Layout/SideNav.tsx
> +  }); //userid에 받는 방식 고려 후, 리팩토링
p3;
커스텀 훅으로 분리해서 에러처리나 로딩처리를 컴포넌트에서 분리하면 어떨까요?

2023-10-26 12:17 UTC, hyesung99 commented on src/pages/Layout/SideNav.tsx
> +  }); //userid에 받는 방식 고려 후, 리팩토링
아마 getMyClub같은 api는 유저의 토큰을 통해 받을것 같은데 axios api request interceptor를 통해 토큰을 넘겨줘도 좋을것 같아요!

2023-10-26 12:54 UTC, SongInjae commented on src/App.tsx
> +    </div>
혜성님 코드에서 들어가 있길래 삭제했습니다!

2023-10-26 12:54 UTC, SongInjae commented on src/apis/users/getMyClub.ts
> +}
아하! 감사합니다:)

2023-10-26 12:56 UTC, SongInjae commented on src/pages/Layout/SideNav.tsx
> +  }); //userid에 받는 방식 고려 후, 리팩토링
넵! 추후에 리팩토링 하도록 하겠습니다!

2023-10-26 13:53 UTC, colorkite10 submitted a review, later dismissed
수고 많으셨습니다 😭😭😭

2023-10-27 02:16 UTC, hyesung99 approved these changes

2023-10-27 03:21 UTC, colorkite10 approved these changes

2023-10-27 04:10 UTC, merged

2023-10-27 05:03 UTC, hyesung99 commented on src/App.tsx
> +    </div>
이거 삭제하면 안돼요...! tanstac-query를 위한 설정입니다...!

2023-10-27 05:08 UTC, hyesung99 commented on src/App.tsx
> +    </div>
아아 제가 만들어서 인재님이 만드신걸 삭제했다는 뜻인가요?