SKRF-167 feat Tab component 구현 with context
Space-Club/Frontend pull request #29
Opened 2023-10-26 14:57 UTC by colorkite10

## 📝요구사항과 구현내용
### Tab 컴포넌트
- context를 사용하여 Tab컴포넌트를 구현했습니다. 
- 각각의 탭의 width와 전체 탭 width를 받을 수 있습니다.
- TabItem컴포넌트는 선택된 탭(ex. 공연)에 해당하는 아이템들(ex. 생성된 공연들)을 렌더링할 때 사용됩니다. 

Tab 컴포넌트 사용 예시
```javascript
return (
    <TabContextProvider>
      <Header style={{ justifyContent: 'end' }}>
        <Tab
          active={`${TAB_CONSTANTS.PERFORMANCE}`}
          maxWidth="13"
          defaultTab={`${TAB_CONSTANTS.PERFORMANCE}`}
          tabItems={[
            {
              title: `${TAB_CONSTANTS.PERFORMANCE}`,
              width: '3',
            },
            {
              title: `${TAB_CONSTANTS.EVENT_SHOW}`,
              width: '3',
            },
            {
              title: `${TAB_CONSTANTS.RECRUITMENT}`,
              width: '4',
            },
          ]}
        />
      </Header>
    </TabContextProvider>
  );
```

### Header 컴포넌트
- Header 컴포넌트에 style 프로퍼티를 추가할 수 있습니다. 
- 헤더로 감싸고 싶은 컴포넌트들의 정렬을 style로 지정해줄 수 있습니다. 

## 구현 스크린샷
![image](https://github.com/Space-Club/Frontend/assets/98521882/dbdb1e2d-e472-479f-ac46-1ba09421504a)

## ✨pr포인트 & 궁금한 점 
- Tab컴포넌트를 이전 프로젝트에서 사용했어서 참고하여 작성했습니다. 궁금한 점 있으시면 마음껏 물어봐주세요! 답변 하면서 저도 공부하겠습니다..
- recoil을 적용해야 하는데 아직 공부 중입니다...!

2023-10-27 06:59 UTC, SongInjae submitted a review, later dismissed
useContext관련된 코드들 보면서 공부할 겸 잘 읽어본 것 같습니다!
고생하셨습니다:)

2023-10-27 06:59 UTC, SongInjae commented on src/context/TabContext.tsx
> +export default TabContext;
저희 상태관리는 recoil을 사용하는 것으로 알고 있었는데,
둘 다 사용하는 것인지 궁금합니다:)

2023-10-27 10:15 UTC, hyesung99 requested changes
고생하셨습니다 채연님!
context랑 커스텀훅 작성하느라 머리가 꽤 아프셨을것 같아요ㅋㅋ

2023-10-27 10:15 UTC, hyesung99 commented on src/components/common/Tab/Tab.tsx
> +};
p2;
기본 탭은 0번째 인덱스로 하면 되지 않을까요??
그렇게하면 최종적으로 다음과 같은 형태가 되겠네요!
```tsx
const Tab = ({ maxWidth, tabItems }: TabProps) => {
  const { activeTab, setActiveTab } = useTabContext();

  useLayoutEffect(() => {
    setActiveTab(tabItems[0].title);
  }, [setActiveTab, tabItems]);

  return (
    <TabContainerStyled maxWidth={maxWidth}>
      {tabItems.map((tabItem, index) => {
        return (
          <>
            <TabItemStyled
              key={index}
              isActive={activeTab === tabItem.title}
              onClick={() => {
                setActiveTab(tabItem.title);
              }}
            >
              {tabItem.title}
            </TabItemStyled>
          </>
        );
      })}
    </TabContainerStyled>
  );
};
```

2023-10-28 02:02 UTC, colorkite10 commented on src/components/common/Header/Header.tsx
![image](https://github.com/Space-Club/Frontend/assets/98521882/fc48b444-e20c-4e1c-adba-ad6fa54d46e1)

@SongInjae 
확인해보니 상하 스크롤이 생기는 이유는 Layout.style.ts에서 레이아웃 Container가 height:100로 해서 생기는 것 같습니다...!
그리고 사이드바 여백을 제외하고 좌우 margin이 같아야하는데, 사이드바 때문에 왼쪽 여백이 가려져서 화면상에서 요소들이 정확히 중간에 있는 것처럼 보이지 않습니다.

![image](https://github.com/Space-Club/Frontend/assets/98521882/2ab19cb2-634c-49ae-bb30-b00c6f7d8740)

좌우 스크롤이 생기는 이유는 Header컴포넌트에 min-width를 60rem으로 걸어놨기 때문입니다...! 화면에 따라 동적으로 헤더 요소들의 크기가 바뀌는 걸 원하시는 걸까요?

2023-10-28 02:40 UTC, colorkite10 commented on src/components/common/Tab/Tab.tsx
> +  const activeIndex = getKeyByValue(TAB_CONSTANTS, activeTab);
TAB_CONSTANTS에서 인덱스처럼 쓰여서 인덱스라고 썼었습니다! activeTabKey 이런 식으로 바꾸면 될까요?👀👀👀

2023-10-28 03:12 UTC, colorkite10 commented on src/components/common/Tab/Tab.tsx
> +        const isActive = TAB_CONSTANTS[activeIndex as keyof typeof TAB_CONSTANTS] === tabItem.title;
just ask; activeIndex는 TAB_CONSTANTS의 키중 하나를 받고 있는데도 단언문을 쓰는 게 어색할까요?

2023-10-28 03:30 UTC, colorkite10 commented on src/utils/getKeyByValue.ts
> +}
그럼 activeIndex의 타입이 string | undefined가 되지 않나요? TAB_CONSTANTS에서 index로 쓰일 수 없게 됩니다...! 타입스크립트 어렵네요 ...

2023-10-28 04:09 UTC, colorkite10 commented on src/components/common/Tab/Tab.style.ts
> +`;
오 이렇게 구분선을 스타일로 처리할 수 있는지 몰랐네요! 감사합니다. 
+) 적용 해봤는데
![image](https://github.com/Space-Club/Frontend/assets/98521882/8c30a539-9363-4778-aa34-1a6d284e1db3)
왜 구분선 두께가 다를까요? 개발자 도구로 ::after를 확인해도 width는 같게 나오는데 말입니다...

2023-10-28 05:04 UTC, hyesung99 commented on src/components/common/Tab/Tab.style.ts
> +`;
음...혹시 border가 적용되어있는거 아닐까요?

2023-10-28 05:07 UTC, hyesung99 commented on src/components/common/Tab/Tab.tsx
> +  const activeIndex = getKeyByValue(TAB_CONSTANTS, activeTab);
index는 정수가 나오길 기대할것 같아요! key값으로 쓴다면 key가 더 어울리겠네요!

2023-10-28 05:08 UTC, hyesung99 commented on src/utils/getKeyByValue.ts
> +}
원래함수를 써도 null을 반환하기 때문에 activeIndex의 타입이 string | null이라 타입단언을 사용한거 아니었나요?

2023-10-28 05:09 UTC, hyesung99 commented on src/components/common/Tab/Tab.tsx
> +        const isActive = TAB_CONSTANTS[activeIndex as keyof typeof TAB_CONSTANTS] === tabItem.title;
activeIndex null일수도 있으니까 ts가 오류를 잡지 못하는경우가 생길것 같아요!

2023-10-28 07:55 UTC, SongInjae approved these changes
고생하셨습니다:)

2023-10-28 07:55 UTC, SongInjae commented on src/components/common/Tab/Tab.style.ts
> +  width: fit-content;
오옹~ fit-content에 대해서는 처음알았네요!! 감사합니다:)

2023-10-28 10:59 UTC, hyesung99 approved these changes

2023-10-28 17:03 UTC, merged