Skrf 156 feat event write info UI
Space-Club/Frontend pull request #34
Opened 2023-10-28 07:49 UTC by SongInjae

## 📝요구사항과 구현내용
- 작업 내용 1: 행사폼에 대한 정보 작성 폼 페이지를 구현했습니다.

## 구현 스크린샷
<img width="1440" alt="스크린샷 2023-10-28 오후 4 30 18" src="https://github.com/Space-Club/Frontend/assets/44944877/7f42c173-7730-44c4-9fba-037dc877d6b8">

<img width="1440" alt="스크린샷 2023-10-28 오후 4 30 27" src="https://github.com/Space-Club/Frontend/assets/44944877/8b0b111f-9d82-4c14-9c25-8206256649b0">

## ✨pr포인트 & 궁금한 점 
- PR Merge후에 기능을 구현하면, 시간 내에 구현이 어려울 것 같아
현 브랜치에서 진행한 뒤에 다시 PR올리겠습니다.

2023-10-28 12:49 UTC, hyesung99 submitted a review, later dismissed

2023-10-28 17:06 UTC, colorkite10 approved these changes

2023-10-29 08:42 UTC, colorkite10 reviewed
수고하셨습니다! 빌드테스트 오류가 났네요... 
리액트 훅 폼 때문에 고생하신 것 같은데 사용해보시니 어떠신가요? 👀👀

2023-10-29 08:43 UTC, colorkite10 approved these changes

2023-10-29 09:49 UTC, hyesung99 requested changes
인재님 고생하셨습니다 양이 아주 많네요!
api명세와 맞지 않는 부분이 좀 있는것 같아요ㅠㅠ
지금은 UI만 집중하고 api에 대한 작업은 나중에 하실 예정이신건가요!

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.tsx
> +      await postUser({ name, number });
이 부분 useMutation으로 리팩토링할 예정이신가요?

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.tsx
>    };
p3;
validation 로직이 page의 역할인가? 싶네요! utils로 빠질 수 있을것 같아요ㅎㅎ

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.tsx
>    };
이런 로직들은 추후 다른 페이지에서도 쓰일 수 있을것 같아요!

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.tsx
>    };
p2;
태그가 form이기 때문에 event.preventDefault 해야 할 것 같은데 문제 없었나요?

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.style.ts
>  `;
p2;
컨테이너 변수 컨벤션!

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.style.ts
>    font-size: 20px;
p1;
font-size는 Theme에 등록된 사이즈로 통일해주세요!

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.tsx
> +    <Container onSubmit={handleSubmit(handleFormSubmit)}>
p4;
handler안에 handler가 있으니까 어색한 느낌??
공식문서에서는
```jsx
onSubmit={handleSubmit(onRegisterFormSubmit)}
```
이런느낌은 어떨까요? 공식문서에서도 이런 방식을 사용하는 것 같네요!

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/RegisterPage/RegisterPage.tsx
> +      <SubmitBtn type="submit">가입 완료</SubmitBtn>
p1;
컨벤션) 줄임말 쓰지 않기!
btn => button

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/event/WriteEventInfoPage/PerformanceForm/PerformanceForm.tsx
> +          rows={10}
p4;
반복되는 구조가 보이는것 같은데 반복문으로 해결할 방법은 없을까요?
상수로 구조화하여 해결할 수도 있었을것 같아요!

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/event/WriteEventInfoPage/RecruitForm/RecruitForm.tsx
> +import React from 'react';
p1;
React는 지워주세요!

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/event/WriteEventInfoPage/WriteEventInfoPage.tsx
> +  return <>{content}</>;
p4;
return 안에서 바로 분기처리하는 방법도 있을것 같네요! 그럼 state를 사용하지 않아도 될것 같아요!

2023-10-29 09:49 UTC, hyesung99 commented on src/apis/event/postPerformanceForm.ts
> +};
p2;
response와 request에 대한 타입 정의는 따로 해주세요!

2023-10-29 09:49 UTC, hyesung99 commented on src/apis/event/postPerformanceForm.ts
> +};
```json
{
		"category": "공연",              
		"clubId": 1,                     
		"eventInfo": {
				"title": "스클 행사",         
				"content": "aaa"      
				"startDate": "2023-10-23",
				"startTime": "15:30:30"
				"location": "대학교 정문",  
				"capacity": 1,       
		},
		"ticketInfo": {
				"cost": 5000,             
				"maxTicketCount": 1,
		},
		"bankInfo": {
				"name": "신한은행",
				"accountNumber": "110-111-11111",
		},
		"formInfo": {
				"openDate": "2023-10-23",
				"openTime": "15:30:00",
				"closeDate": "2023-10-23",
				"closeTime": "15:30:00",
		},
}
```
api 명세에 request가 이렇게 되어 있는데 명세와 맞지 않는것 같네요...!
행사 타입은 url이 따로 있는게 아니라 body에 category를 통해 해야하는것 같아요ㅠㅠ

2023-10-29 09:49 UTC, hyesung99 commented on src/pages/event/WriteEventInfoPage/PerformanceForm/PerformanceForm.tsx
> +      await postPerformanceForm({ data });
p2;
지금 api요청 부분이 전부 단순 axios요청으로 되어있는것 같은데 tanstack-query는 의도적으로 사용하지 않으신건가요?

2023-10-30 08:23 UTC, SongInjae commented on src/pages/event/WriteEventInfoPage/PerformanceForm/PerformanceForm.tsx
> +          rows={10}
각 폼마다 사용하는 컴포넌트와, 설정들도 달라서 어떻게 해야할지 감이 안오네요....ㅠㅡㅠ

2023-10-31 02:31 UTC, SongInjae commented on src/pages/RegisterPage/RegisterPage.tsx
> +      await postUser({ name, number });
아 바로 반영하겠습니다! 감사합니다:)

2023-10-31 02:36 UTC, SongInjae commented on src/pages/RegisterPage/RegisterPage.tsx
>    };
헉 좋은 의견 감사합니다:)

2023-10-31 02:38 UTC, SongInjae commented on src/pages/RegisterPage/RegisterPage.style.ts
>  `;
넵 반영하겠습니다:)

2023-10-31 02:39 UTC, SongInjae commented on src/pages/RegisterPage/RegisterPage.style.ts
>    font-size: 20px;
헉 px이였군요! 반영하겠습니다:)

2023-10-31 02:46 UTC, SongInjae commented on src/pages/RegisterPage/RegisterPage.tsx
> +    <Container onSubmit={handleSubmit(handleFormSubmit)}>
넵 RegisterPage와 PerformaceFormPage 모두 적용하겠습니다! 감사합니다:)

2023-10-31 02:47 UTC, SongInjae commented on src/pages/RegisterPage/RegisterPage.tsx
> +      <SubmitBtn type="submit">가입 완료</SubmitBtn>
넵 감사합니다:)

2023-10-31 02:49 UTC, SongInjae commented on src/pages/event/WriteEventInfoPage/RecruitForm/RecruitForm.tsx
> +import React from 'react';
넵!

2023-10-31 02:50 UTC, SongInjae commented on src/apis/event/postPerformanceForm.ts
> +};
넵 좋은 지적 감사합니다!!

2023-10-31 02:53 UTC, SongInjae commented on src/pages/RegisterPage/RegisterPage.tsx
>    };
네 문제없이 잘 작동합니다!

2023-10-31 02:58 UTC, SongInjae commented on src/pages/event/WriteEventInfoPage/WriteEventInfoPage.tsx
> +  return <>{content}</>;
오호 그 생각을 하지 못했군요! 감사합니다:)

2023-10-31 06:20 UTC, colorkite10 submitted a review, later dismissed

2023-10-31 06:52 UTC, colorkite10 approved these changes

2023-10-31 06:52 UTC, colorkite10 commented on src/apis/event/postPerformanceForm.ts
> +export default postPerformanceForm;
참고하겠습니다1! 정말 고생하셨습니다 👏👏👏👏

2023-10-31 07:17 UTC, hyesung99 submitted a review, later dismissed

2023-10-31 07:27 UTC, merged