SKRF-217 refactor: Tab컴포넌트 완성, 홈페이지에 적용 및 클럽 홈 페이지에 추가
Space-Club/Frontend pull request #72
Opened 2023-11-08 17:05 UTC by colorkite10

## 📝요구사항과 구현내용
-  탭 컴포넌트 완성했습니다! 
- 메인 페이지에 적용해 놓았습니다.
- 클럽 홈페이지에는 헤더에 탭만 넣어 놨고, 딱히 기능은 하지 않습니다. (TODO: link에 navigate할 주소 넣어줘야 함)

## 구현 스크린샷

## ✨pr포인트 & 궁금한 점 
- 브랜치 이동하셔서 직접 동작하는 걸 보시면 이해가 빠를 것 같습니다...!
- 많은 피드백 바랍니다...!

2023-11-09 05:08 UTC, hyesung99 requested changes

2023-11-09 05:08 UTC, hyesung99 commented on src/pages/ProfilePage/ProfilePage.tsx
> +        </TabItem>
p3;
index보다는 tabName이라는 속성명이 어떨까요?

Render ~ 는 함수의 느낌이 나서 그냥 <ApplyEvent/>이어도 될것 같아요!
저는 내가 신청한 이벤트 MyEvent로 했는데
ApplyEvent는 동사니까 함수명 같은 느낌이 나요!
AppliedEvent가 맞을것 같아요!
MyEvent 또는 AppliedEvent로 컴포넌트 명이 통일되어야 겠네요! 컴포넌트 명도 MyEventCard 아닌 AppliedEventCard 같은 식으로..!

변수명 결정은 채연님에게 맡기겠습니다! 통일만 부탁드려요!

2023-11-09 05:08 UTC, hyesung99 commented on src/pages/club/ClubHomePage/ClubHomePage.tsx
> +        </ClubHomePageContainer>
just ask;
클럽 홈도 라우팅 방식으로 하지 않고 전역상태을 통해 다른 페이지를 렌더링 하는걸 생각하시나요?

2023-11-10 03:54 UTC, colorkite10 commented on src/pages/MainPage/MainPage.tsx
> +        </TabItem>
그럼 eventType과 data도 변경될 때마다 업데이트 해주는 로직이 필요하지 않나요? useEffect...같은...
메인 페이지는 종류와 상관 없이 똑같이 생겼으니까 위 방식이 가능하다면 혜성님 말씀대로 하는 게 좋을 것 같습니다!

2023-11-10 03:56 UTC, colorkite10 commented on src/pages/ProfilePage/ProfilePage.tsx
> +        </TabItem>
Applied가 맞다고 생각해서 이걸로 통일하려고 했더니 My가 훨씬 많았네요... 노가다 해버린..

2023-11-10 08:20 UTC, hyesung99 commented on src/pages/ProfilePage/ProfilePage.tsx
> +        </TabItem>
ㅋㅋㅋ고생하셧습니다!

2023-11-10 08:25 UTC, hyesung99 approved these changes
채연님 고생하셨습니다!
변경 요구사항이 많았는데 다 이해하고 깔끔하게 해주셨네요💯 
커밋 기록을 보니 노력의 흔적이 보입니다...ㅎㅎ 짱짱

2023-11-10 08:25 UTC, hyesung99 commented on src/constants/event.ts
> +];
p2;
얘네는 contants/tab.ts 에 있으면 좋을것 같아요!

2023-11-10 08:25 UTC, hyesung99 commented on src/pages/club/ClubEventPage/ClubEventPage.tsx
> +              { title: `${TAB_CONSTANTS.CLUB_MANAGE}`, link: `${PATH.CLUB.MANAGE(clubId)}` },
p3;
얘네도 메인페이지처럼 상수화하는거 어떨까요?
constants/tab.ts에!

2023-11-10 08:25 UTC, hyesung99 commented on src/pages/club/ClubHomePage/ClubHomePage.tsx
> +            ]}
요거도!

2023-11-10 08:27 UTC, colorkite10 commented on src/constants/event.ts
> +];
안 그래도 클럽 부분의 탭에 link를 깔끔하게 전달해 주고 싶었는데...
클럽의 Path들은 clubId를 받아서 스트링으로 반환하는 함수라 그냥 string인 다른 path들과 어떻게 처리해줄지 모르겠더라고요... 그래서 새벽 다섯 시까지 고민해봤지만? 도저히 제 머리론 모르겠어서 이렇게 처리했습니다...

2023-11-10 08:28 UTC, colorkite10 commented on src/pages/club/ClubEventPage/ClubEventPage.tsx
> +              { title: `${TAB_CONSTANTS.CLUB_MANAGE}`, link: `${PATH.CLUB.MANAGE(clubId)}` },
안 그래도 클럽 부분의 탭에 tabItems를 깔끔하게 전달해 주고 싶었는데...
클럽의 Path들은 clubId를 받아서 스트링으로 반환하는 함수라 그냥 string인 다른 path들과 어떻게 처리해줄지 모르겠더라고요... 그래서 새벽 다섯 시까지 고민해봤지만? 도저히 제 머리론 모르겠어서 이렇게 처리했습니다...

2023-11-10 08:30 UTC, colorkite10 commented on src/constants/event.ts
> +];
그럼 TABS 상수들은 다 constants/tab.ts로 옮길까요? club탭은 club.ts, 프로필탭은 user.ts에 존재합니다!

2023-11-10 09:34 UTC, hyesung99 commented on src/constants/event.ts
> +];
넵 다 옮기는게 좋을것 같아요!

2023-11-10 09:35 UTC, hyesung99 commented on src/pages/club/ClubEventPage/ClubEventPage.tsx
> +              { title: `${TAB_CONSTANTS.CLUB_MANAGE}`, link: `${PATH.CLUB.MANAGE(clubId)}` },
이거 그대로 가져다 두면 안되나요?

2023-11-10 09:39 UTC, hyesung99 approved these changes

2023-11-10 09:39 UTC, hyesung99 commented on src/pages/club/ClubEventPage/ClubEventPage.tsx
> +              { title: `${TAB_CONSTANTS.CLUB_MANAGE}`, link: `${PATH.CLUB.MANAGE(clubId)}` },
```ts
tabItmes = {CLUB_TAP(clubId)}

.
.
.
const CLUB_TAB = (clubId) => {
              { title: `${TAB_CONSTANTS.CLUB_HOME}`, link: `${PATH.CLUB.HOME(clubId)}` },
              { title: `${TAB_CONSTANTS.CLUB_EVENTS}`, link: `${PATH.CLUB.EVENT(clubId)}` },
              { title: `${TAB_CONSTANTS.CLUB_MANAGE}`, link: `${PATH.CLUB.MANAGE(clubId)}` }
```
이런느낌...?

2023-11-10 09:48 UTC, colorkite10 commented on src/pages/club/ClubEventPage/ClubEventPage.tsx
> +              { title: `${TAB_CONSTANTS.CLUB_MANAGE}`, link: `${PATH.CLUB.MANAGE(clubId)}` },
아니 어제는 왜 안 됐지????? 감사합니다고쳤어요

2023-11-10 11:50 UTC, hyesung99 approved these changes

2023-11-11 07:39 UTC, SongInjae approved these changes
고생하셨습니다:) 리뷰가 늦어 죄송합니다.

2023-11-11 07:39 UTC, SongInjae commented on src/apis/event/getAppliedEvent.ts
> +      size: '10',
just ask.
10개씩으로 무한스크롤로 구현하는 것인가요? 아니면 밑에 나중에 페이지네이션이 들어가나요?

2023-11-11 08:27 UTC, colorkite10 commented on src/apis/event/getAppliedEvent.ts
> +      size: '10',
혜성님이 하신 부분이긴 한데, 페이지네이션으로 할 것 같습니다!

2023-11-11 08:27 UTC, merged